### ISSUE TITLE
Issue on installation

### ISSUE THREAD

**Issue by Shirling-VT** [TheMuonNeutrino/magSonify#27]
Have an issue during pip installation:
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-19ybaavk/setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

Looks like the setup.py file is looking for a file 'README.md' which does not exist.

**Comment by marek-cottingham** [comment]
Hey, sorry about that, setup.py file was really out of date.
Really should build a test for this sort of thing as setting up python package installation is easily confusing.

I've fixed the issue for now.
