### ISSUE TITLE
DataSet, 3D, 1D __init__()

### ISSUE THREAD

**Issue by marek-cottingham** [TheMuonNeutrino/magSonify#5]
DataSet_3D
:param data: specify type is dict
Specify is dict of numpy arrays (numerical)
Specify arrays should be 1D
Specify keys should be **int()** 0, 1 ,2 and optional any

DataSet_1D
:param x: specify type is np.array or dict or np.array with one key(0)

data attr -> specify the same thing

**Comment by marek-cottingham** [comment]
Explain how data works throughly. What are the key? Examples of this. Convention that 'x', 'y' 'z' axes in 3D data (eg. vectors) should be keyed as 0, 1, 2 respectively.

Data is dict of np.array()
Specify extract key exacts a data series, slice extracts a range of samples point across all data series (ie. for a corresponding time range)

**Comment by osdev-in** [comment]
Hey @TheMuonNeutrino , can I work on this ?

**Comment by marek-cottingham** [comment]
Hey @kadatatlukishore , I'm happy to take contributions, so go ahead and submit a pull request.
Out of curiosity, what drew your interest to this project? I wasn't expecting anyone to pay attention at this stage.

**Comment by osdev-in** [comment]
Hey @TheMuonNeutrino , Just searched for good first issues to contribute. But I liked you work here. 
`It allows for downloading of satellite data from CDA web, processing of this data and generation of audio` it catches all the attention and it is really interesting. So would love to add small contribution to this amazing work of yours.

**Comment by marek-cottingham** [comment]
Thank you for your kind words.
Unfortunately, I'm going to go ahead and close this issue as I've manage to address it while working on another related issue.
